[package]
name = "coralia-core"
version = "0.1.0"
edition = "2024"

[dependencies]
coralia-player = { path = "../coralia-player" }
coralia-data = { path = "../coralia-data" }
coralia-gui = { path = "../coralia-gui" }
env_logger = "0.10.2"
tokio = { version = "1", features = ["full"] }
log = "0.4.22"
